nav:
  - Product List: products.md
  - EX-Installer: ex-installer
  - EX-CommandStation: ex-commandstation
  - EX-FastClock: ex-fastclock
  - EX-IOExpander: ex-ioexpander
  - EX-Turntable: ex-turntable
